---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  run_list:
  - recipe[apt]
- name: centos-6.4
- name: centos-5.10

suites:
- name: default
  run_list:
  - recipe[snmp]
  - recipe[snmp::extendbind]
  - recipe[snmp::snmptrapd]
  attributes: {}
